apiVersion: v1
kind: Secret
metadata:
  name: openai-secrets
type: Opaque
data:
  api-key: ${OPENAI_API_KEY_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
type: Opaque
data:
  api-key: ${AZURE_OPENAI_KEY_BASE64}
  endpoint: ${AZURE_OPENAI_ENDPOINT_BASE64}
